### ISSUE TITLE
ModuleNotFoundError: No module named 'esim'

### ISSUE THREAD

**Issue by rzhangpku** [coetaur0/ESIM#5]
No matter in which way, I get the error "ModuleNotFoundError: No module named 'esim'". Thank you very much!
```
➜  preprocessing git:(master) pwd
~/tmp/ESIM/scripts/preprocessing
➜  preprocessing git:(master) python preprocess_snli.py
Traceback (most recent call last):
  File "preprocess_snli.py", line 12, in <module>
    from esim.data import Preprocessor
ModuleNotFoundError: No module named 'esim'
```

```
➜  scripts git:(master) pwd
~/tmp/ESIM/scripts
➜  scripts git:(master) python preprocessing/preprocess_snli.py
Traceback (most recent call last):
  File "preprocessing/preprocess_snli.py", line 12, in <module>
    from esim.data import Preprocessor
ModuleNotFoundError: No module named 'esim'
```

```
➜  ESIM git:(master) pwd
~/tmp/ESIM
➜  ESIM git:(master) python scripts/preprocessing/preprocess_snli.py
Traceback (most recent call last):
  File "scripts/preprocessing/preprocess_snli.py", line 12, in <module>
    from esim.data import Preprocessor
ModuleNotFoundError: No module named 'esim'
```

**Comment by coetaur0** [comment]
Hi, have you installed the package on your machine first ? Before you can use it, you need to install esim with the command `pip install --upgrade .` from within the repository, at its root.

**Comment by rzhangpku** [comment]
Oh! I do not install esim with the command `pip install --upgrade .`
After I install esim, the problem is solved.
Thanks a lot!
